# Generated by Django 6.0.8 on 2026-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('intro', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('students', models.PositiveIntegerField(default=0)),
                ('lessons', models.PositiveIntegerField(default=0)),
                ('duration', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('topics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
